server:
 port: 8080
 servlet:
  context-path: /managePro
spring:

 datasource:
  url: jdbc:mysql://127.0.0.1:3306/test?useSSL=true&userTimezone=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
  username: root
  password: 52o3344587
  driver-class-name: com.mysql.cj.jdbc.Driver

 redis:
  host: 127.0.0.1
  password: qwertasdfg
  port: 6379
  timeout: 9000ms
  jedis:
   pool:
    max-active: 12000
    max-wait: 1ms
    max-idle: 100
    min-idle: 8
 cache:
  redis:
   time-to-live: 300000
   type: redis

mybatis:
 mapper-locations: classpath*:*/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

websocketUrl: ws://127.0.0.1:8057/socket-api/webSocket/proServer

threadName: 消费者线程
consumerThreadName: 消费者线程

uploadFolder: data/upload/
logging:
 level:
  root: info
  com.manage.project.mapper: debug
  org.apache.kafka: info


